name = "startech"
compatibility_date = "2025-03-01"

main = "./worker/index.ts"

routes = [
  { pattern = "startech-innovation.com", custom_domain = true },
  { pattern = "www.startech-innovation.com", custom_domain = true },
]

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[[d1_databases]]
binding = "DB"
database_name = "startech-demos"
database_id = "dd762257-3eee-4e21-897f-6eb580c4f0c7"

[vars]
ENVIRONMENT = "production"
